(()=>{'use strict';
const BASE=['Lucas V.','Lucas R.','Marlon','Ewerson','Everson','Clayton','Wendel','Gabriel','Adriano','Luciano','Juliano','Nattan','Marcio','Christoffer','Patrício','Mateus','Alan','Shaiane','Willians'];
const SLOTS=['18:00','18:30','19:00','19:30','20:00','20:30'],END=1350,MOVE=10,MAX=8000;
const state={step:0,mode:'plan',roster:[...BASE],present:new Set(),current:[],future:[],decisions:{},plan:null,previousPlan:null,roundIndex:0,lastChange:[]};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const uid=()=>Math.random().toString(36).slice(2);
const toMin=t=>{const[h,m]=String(t||'00:00').split(':').map(Number);return h*60+m};
const toTime=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
const overlap=(a,b,c,d)=>Math.max(a,c)<Math.min(b,d);
function aliases(n){const u=norm(n);if(u==='LUCAS V.')return['LUCAS V.','LUCAS V','LUCAS'];if(u==='LUCAS R.')return['LUCAS R.','LUCAS R'];if(u==='MARCIO')return['MARCIO','MÁRCIO'];return[n]}
function toast(x){const e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1600)}
function renderRoster(){$('#roster').innerHTML=state.roster.map(n=>`<button class="chip ${state.present.has(n)?'sel':''}" data-person="${n}">${n}</button>`).join('');$$('[data-person]').forEach(b=>b.onclick=()=>{state.present.has(b.dataset.person)?state.present.delete(b.dataset.person):state.present.add(b.dataset.person);renderRoster()});$('#count').textContent=`${state.present.size} presentes`}
function ownerOf(line){const u=norm(line);return[...state.present].sort((a,b)=>b.length-a.length).find(n=>aliases(n).some(a=>new RegExp(`(^|[^A-Z0-9])${norm(a).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^A-Z0-9]|$)`).test(u)))||null}
function parseReport(raw){let sec='ignore';const cur=[],fut=[];for(const r of raw.split(/\n/)){const line=r.trim();if(!line)continue;const u=norm(line).replace(/\*/g,'').replace(/:$/,'');if(u==='SETUP'||u.includes('MAQUINAS EM SETUP')){sec='setup';continue}if(u==='AJUSTES'||u.includes('MAQUINAS EM AJUSTES')){sec='adjust';continue}if(u.includes('PROXIMOS SETUPS')){sec='future';continue}if(u.includes('MANUTENCAO')||u.includes('SETUPS 1')||u.includes('SETUPS 3')||u.includes('SELECAO')||u.includes('BOM TRABALHO')){sec='ignore';continue}if(!['setup','adjust','future'].includes(sec))continue;const mm=line.match(/TNL\s*0*(\d{1,3})/i);if(!mm)continue;const machine=`TNL ${String(mm[1]).padStart(3,'0')}`,time=(line.match(/\b(\d{1,2}:\d{2})\b/)||[])[1]||'20:30';if(sec==='future'){if(!fut.some(x=>x.machine===machine))fut.push({id:uid(),machine,start:time});continue}if(line.includes('✅'))continue;const owner=ownerOf(line);if(owner&&!cur.some(x=>x.machine===machine&&x.owner===owner))cur.push({id:uid(),type:sec,machine,owner})}
state.current=cur;state.future=fut.sort((a,b)=>toMin(a.start)-toMin(b.start));state.decisions={};state.roundIndex=0;state.mode='plan';state.previousPlan=null;state.lastChange=[];recalculate();return cur.length+fut.length>0}
function initialFree(name,decisions=state.decisions){const acts=state.current.filter(a=>a.owner===name);if(!acts.length)return 1080;let free=1080;for(const a of acts){const d=decisions[a.id];if(!d)return END;if(d.kind==='finish')free=Math.max(free,toMin(d.finish)+MOVE);else free=END}return free}
function cloneEvents(e){const o={};for(const[k,v]of Object.entries(e))o[k]=v.map(x=>({...x}));return o}
function freeAt(events,n,s,e){return!(events[n]||[]).some(x=>overlap(x.s,x.e,s,e))}
function addEvent(events,n,s,e,type,meta={}){(events[n]||(events[n]=[])).push({s,e,type,...meta})}
function planConflicts(plan){const out=[];for(const name of state.present){const events=[...(plan?.events?.[name]||[])].sort((a,b)=>a.s-b.s||a.e-b.e);for(let i=1;i<events.length;i++)if(overlap(events[i-1].s,events[i-1].e,events[i].s,events[i].e))out.push(`${name} tem atividades sobrepostas às ${toTime(events[i].s)}`)}return out}
function better(a,b){if(!b)return true;const ka=[a.futureCount,a.coverCount,a.dinnerCount,-a.uncovered,-a.changeCount,a.reserve],kb=[b.futureCount,b.coverCount,b.dinnerCount,-b.uncovered,-b.changeCount,b.reserve];for(let i=0;i<ka.length;i++)if(ka[i]!==kb[i])return ka[i]>kb[i];return false}
function buildPlan(extraDecision=null){const people=[...state.present],decisions={...state.decisions};if(extraDecision)decisions[extraDecision.id]=extraDecision.value;const futures=state.future,needs=state.current.filter(a=>decisions[a.id]?.kind==='cover').map(a=>({id:a.id,owner:a.owner,machine:a.machine,preferred:decisions[a.id].dinner}));let tested=0,best=null;const choices=[...futures.map(x=>({kind:'future',item:x})),...needs.map(x=>({kind:'cover',item:x}))];
function dfs(i,assign,covers,events){if(tested>=MAX)return;if(i===choices.length){tested++;evaluate(assign,covers,events);return}const ch=choices[i];if(ch.kind==='future'){const s=toMin(ch.item.start);for(const n of people){if(initialFree(n,decisions)>s||!freeAt(events,n,s,END))continue;const ev=cloneEvents(events);addEvent(ev,n,s,END,'future',{machine:ch.item.machine,id:ch.item.id});dfs(i+1,{...assign,[ch.item.id]:n},covers,ev)}dfs(i+1,{...assign,[ch.item.id]:null},covers,events)}else{const times=ch.item.preferred?[ch.item.preferred]:SLOTS;for(const t of times){const s=toMin(t),e=s+60;for(const n of people){if(n===ch.item.owner||initialFree(n,decisions)>s||!freeAt(events,n,s,e))continue;const ev=cloneEvents(events);addEvent(ev,n,s,e,'cover',{machine:ch.item.machine,id:ch.item.id});dfs(i+1,assign,{...covers,[ch.item.id]:{name:n,time:t}},ev)}}dfs(i+1,assign,{...covers,[ch.item.id]:null},events)}}
function evaluate(assign,covers,events){const ev=cloneEvents(events),dinners={};for(const need of needs){const c=covers[need.id];if(!c)continue;const s=toMin(c.time),e=s+60;if(freeAt(ev,need.owner,s,e)){addEvent(ev,need.owner,s,e,'dinner',{machine:need.machine});dinners[need.owner]={start:c.time,end:toTime(e)}}}
for(const name of people){if(dinners[name])continue;for(const t of SLOTS){const s=toMin(t),e=s+60;if(initialFree(name,decisions)>s||!freeAt(ev,name,s,e))continue;addEvent(ev,name,s,e,'dinner');dinners[name]={start:t,end:toTime(e)};break}}
let futureCount=0,coverCount=0,uncovered=0,reserve=0;for(const f of futures)assign[f.id]?futureCount++:uncovered++;for(const n of needs)covers[n.id]?coverCount++:uncovered++;for(const p of people){const busy=(ev[p]||[]).reduce((s,x)=>s+x.e-x.s,0);reserve+=Math.max(0,270-busy)}const plan={assign,covers,events:ev,dinners,dinnerCount:Object.keys(dinners).length,futureCount,coverCount,uncovered,reserve,tested};plan.changeCount=diffPlans(state.plan,plan).length;if(planConflicts(plan).length)return;if(better(plan,best))best=plan}
dfs(0,{}, {},{});return best||{assign:{},covers:{},events:{},dinners:{},dinnerCount:0,futureCount:0,coverCount:0,uncovered:futures.length+needs.length,tested,changeCount:99}}
function diffPlans(oldP,newP){if(!oldP)return[];const out=[];for(const f of state.future){const a=oldP.assign?.[f.id]||'sem responsável',b=newP.assign?.[f.id]||'sem responsável';if(a!==b)out.push(`${f.machine}: ${a} → ${b}`)}for(const a of state.current){const x=oldP.covers?.[a.id],y=newP.covers?.[a.id],ax=x?`${x.name} ${x.time}`:'sem cobertura',by=y?`${y.name} ${y.time}`:'sem cobertura';if(ax!==by)out.push(`${a.machine}: ${ax} → ${by}`)}for(const name of state.present){const a=oldP.dinners?.[name]?.start||'sem jantar',b=newP.dinners?.[name]?.start||'sem jantar';if(a!==b)out.push(`${name}: jantar ${a} → ${b}`)}return out}
function recalculate(extra=null){const old=state.plan,next=buildPlan(extra);state.previousPlan=old;state.plan=next;state.lastChange=diffPlans(old,next).slice(0,6)}
function showSheet(html){const s=$('#sheet');s.innerHTML=`<div class="sheet-backdrop"><div class="sheet"><div class="sheet-handle"></div>${html}</div></div>`;s.querySelector('.sheet-backdrop').onclick=e=>{if(e.target===e.currentTarget)closeSheet()}}
function closeSheet(){$('#sheet').innerHTML=''}
function planList(){return state.future.map(f=>`<div class="setup-row ${state.plan.assign[f.id]?'ok':''}"><time>${f.start}</time><div><strong>${f.machine}</strong><span>${state.plan.assign[f.id]||'Sem responsável'}</span></div><i>${state.plan.assign[f.id]?'✓':'!'}</i></div>`).join('')}
function renderInitialPlan(){const all=state.plan.futureCount===state.future.length;return`<div class="status-banner ${all?'good':'warn'}"><strong>${all?'Próximos setups cobertos':'Plano inicial incompleto'}</strong><span>${all?'Todos os próximos setups possuem responsável.':'A ronda pode liberar pessoas e melhorar o plano.'}</span></div><div class="setup-list">${planList()}</div><button id="startRound" class="btn primary full">Iniciar ronda de jantares</button>`}
function nextActivity(){while(state.roundIndex<state.current.length&&state.decisions[state.current[state.roundIndex].id])state.roundIndex++;return state.current[state.roundIndex]||null}
function slotAnalysis(a,time){const candidate=buildPlan({id:a.id,value:{kind:'cover',dinner:time}}),cover=candidate.covers[a.id],conflicts=planConflicts(candidate),allSetups=candidate.futureCount===state.future.length,allDinners=candidate.dinnerCount===state.present.size;let level='bad',title='Não recomendado',reason='Não foi possível atender tudo neste horário.';if(cover&&allSetups&&allDinners&&!conflicts.length){level='best';title='Funciona completo';reason=`${cover.name} cobre ${a.machine}. Todos os setups e jantares continuam atendidos.`}else if(cover&&allSetups&&!conflicts.length){level='ok';title='Funciona';reason=`${cover.name} cobre ${a.machine}. Setups mantidos; ainda faltam jantares a definir.`}else if(cover){level='warn';title='Possível com impacto';reason=`${cover.name} cobre ${a.machine}, mas o plano fica com pendências.`}return{time,candidate,cover,level,title,reason,changes:diffPlans(state.plan,candidate)}}
function renderRoundCard(){const a=nextActivity();if(!a)return`<div class="status-banner good"><strong>Ronda concluída</strong><span>Todas as atividades foram confirmadas.</span></div><button id="goFinal" class="btn primary full">Abrir plano final</button>`;const analyses=SLOTS.map(t=>slotAnalysis(a,t));const best=analyses.find(x=>x.level==='best')||analyses.find(x=>x.level==='ok');return`<div class="round-summary"><span>${state.roundIndex+1} de ${state.current.length}</span><b>${state.plan.futureCount===state.future.length?'Setups cobertos':'Há setups pendentes'}</b><b>${state.plan.dinnerCount}/${state.present.size} jantares definidos</b></div><div class="person-card"><header><div><small>${a.type==='setup'?'SETUP EM ANDAMENTO':'AJUSTE EM ANDAMENTO'}</small><h3>${a.owner}</h3><span>${a.machine}</span></div><em>${best?`Melhor: ${best.time}`:'Sem opção completa'}</em></header><div class="person-question">Que horas ${a.owner} quer jantar?</div><div class="slot-grid">${analyses.map(x=>`<button class="slot ${x.level}" data-slot="${x.time}"><strong>${x.time}</strong><small>${x.title}</small><span>${x.cover?`${x.cover.name} cobre`:'Sem cobertura'}</span></button>`).join('')}</div><div class="slot-note">Toque em um horário para ver exatamente quem janta, quem cobre e o impacto no restante do turno.</div></div>`}
function confirmSlot(a,analysis){const dinnerEnd=toTime(toMin(analysis.time)+60),cover=analysis.cover,coverDinner=cover?analysis.candidate.dinners?.[cover.name]:null,allSetups=analysis.candidate.futureCount===state.future.length,allDinners=analysis.candidate.dinnerCount===state.present.size;showSheet(`<div class="sheet-kicker">CONFIRMAR HORÁRIO</div><h3>${a.owner} janta ${analysis.time}–${dinnerEnd}</h3><div class="decision-people"><div><small>${a.owner}</small><strong>Jantar ${analysis.time}–${dinnerEnd}</strong><span>${a.machine}</span></div>${cover?`<div><small>${cover.name}</small><strong>Jantar ${coverDinner?`${coverDinner.start}–${coverDinner.end}`:'a definir'}</strong><span>Cobre ${a.machine} ${analysis.time}–${dinnerEnd}</span></div>`:''}</div><div class="result-box ${allSetups&&allDinners?'good':'warn'}"><b>Resultado do turno</b><span>${allSetups?'✓ Todos os próximos setups atendidos':'! Há setup sem responsável'}</span><span>${allDinners?'✓ Todos os jantares atendidos':`! ${state.present.size-analysis.candidate.dinnerCount} jantares ainda pendentes`}</span><span>${planConflicts(analysis.candidate).length?'! Há conflito de horário':'✓ Nenhum conflito de horário'}</span>${analysis.changes.length?`<details><summary>Ver alterações automáticas</summary>${analysis.changes.slice(0,8).map(x=>`<p>${x}</p>`).join('')}</details>`:''}</div><div class="sheet-actions"><button class="btn secondary" id="cancelSheet">Voltar</button><button class="btn primary" id="confirmDecision">Confirmar horário</button></div>`);$('#cancelSheet').onclick=closeSheet;$('#confirmDecision').onclick=()=>{state.decisions[a.id]={kind:'cover',dinner:analysis.time};state.previousPlan=state.plan;state.plan=analysis.candidate;state.lastChange=analysis.changes.slice(0,6);state.roundIndex++;closeSheet();renderRound()}}
function bindRound(){const a=nextActivity();if(!a){$('#goFinal')&&($('#goFinal').onclick=()=>{state.step=3;update()});return}$$('[data-slot]').forEach(btn=>btn.onclick=()=>confirmSlot(a,slotAnalysis(a,btn.dataset.slot)))}
function renderRound(){if(state.mode==='plan')$('#round').innerHTML=renderInitialPlan();else $('#round').innerHTML=renderRoundCard();$('#startRound')&&($('#startRound').onclick=()=>{state.mode='round';renderRound()});if(state.mode==='round')bindRound()}
function personTimeline(name){const events=[];const acts=state.current.filter(a=>a.owner===name);if(acts.length)for(const a of acts)events.push({sort:0,time:'Agora',text:`${a.type==='setup'?'Setup':'Ajuste'} ${a.machine}`});else events.push({sort:0,time:'Agora',text:'Livre'});const dinner=state.plan.dinners?.[name];if(dinner)events.push({sort:toMin(dinner.start),time:dinner.start,text:`Jantar ${dinner.start}–${dinner.end}`});else events.push({sort:9999,time:'—',text:'Jantar não definido'});for(const a of state.current){const c=state.plan.covers[a.id];if(c?.name===name)events.push({sort:toMin(c.time),time:c.time,text:`Cobre ${a.owner} na ${a.machine}`})}for(const f of state.future)if(state.plan.assign[f.id]===name)events.push({sort:toMin(f.start),time:f.start,text:`Inicia ${f.machine}`});return events.sort((a,b)=>a.sort-b.sort||a.text.localeCompare(b.text))}
function peopleReport(){return[...state.present].map(name=>({name,events:personTimeline(name)})).sort((a,b)=>a.name.localeCompare(b.name))}
function pendingItems(){const p=[];for(const f of state.future)if(!state.plan.assign[f.id])p.push(`${f.start} - ${f.machine} sem responsável`);for(const name of state.present)if(!state.plan.dinners?.[name])p.push(`${name} sem jantar definido`);p.push(...planConflicts(state.plan));return[...new Set(p)]}
function whatsapp(){let txt='*REVEZAMENTO*\n\n';for(const p of peopleReport()){txt+=`*${p.name.toUpperCase()}*\n`;for(const e of p.events)txt+=`${e.time} - ${e.text}\n`;txt+='\n'}txt+='*PRÓXIMOS SETUPS*\n\n';for(const f of state.future)txt+=`${f.start} - ${f.machine} - ${state.plan.assign[f.id]||'SEM RESPONSÁVEL'}\n`;const pend=pendingItems();txt+='\n*PENDÊNCIAS*\n'+(pend.length?pend.join('\n'):'Nenhuma');return txt}
function renderFinal(){const people=peopleReport(),pend=pendingItems(),valid=!pend.length;$('#final').innerHTML=`<div class="final-hero ${valid?'good':'warn'}"><strong>${valid?'Turno organizado':'Plano com pendências'}</strong><span>${state.plan.futureCount===state.future.length?'Todos os setups cobertos':'Existem setups sem responsável'}</span><span>${state.plan.dinnerCount===state.present.size?'Todos possuem jantar':'Ainda faltam jantares'}</span><span>${planConflicts(state.plan).length?'Há conflitos de horário':'Nenhum conflito encontrado'}</span></div><h3 class="final-section-title">Equipe</h3><div class="team-board">${people.map(p=>{const dinner=state.plan.dinners?.[p.name];const cover=p.events.find(e=>e.text.startsWith('Cobre'));const setup=p.events.find(e=>e.text.startsWith('Inicia'));return`<section><header><strong>${p.name}</strong><span>${dinner?`Jantar ${dinner.start}`:'Jantar pendente'}</span></header>${cover?`<p>↔ ${cover.time} ${cover.text}</p>`:''}${setup?`<p>⚙ ${setup.time} ${setup.text}</p>`:''}</section>`}).join('')}</div><h3 class="final-section-title">Próximos setups</h3><div class="setup-list">${planList()}</div>${pend.length?`<div class="pending-box"><strong>Pendências</strong>${pend.map(x=>`<span>${x}</span>`).join('')}</div>`:`<div class="status-banner good"><strong>Nenhuma pendência</strong><span>Plano pronto para uso.</span></div>`}<button id="copyWA" class="btn primary full">Copiar para WhatsApp</button><textarea id="waText" class="wa-text" hidden>${whatsapp()}</textarea>`;$('#copyWA').onclick=async()=>{try{await navigator.clipboard.writeText(whatsapp());toast('Plano copiado')}catch{const t=$('#waText');t.hidden=false;t.select();document.execCommand('copy');toast('Plano copiado')}}}
function update(){$$('.step').forEach((e,i)=>e.classList.toggle('active',i===state.step));$$('.progress span').forEach((e,i)=>e.classList.toggle('on',i<=state.step));$('#back').style.visibility=state.step===0?'hidden':'visible';$('#next').textContent=state.step===2?(nextActivity()?'Concluir ronda':'Ver plano final'):state.step===3?'Voltar ao planejamento':'Continuar';if(state.step===2)renderRound();if(state.step===3)renderFinal();scrollTo(0,0)}
$('#addName').onclick=()=>{const i=$('#newName'),v=i.value.trim();if(!v)return;let n=state.roster.find(x=>norm(x)===norm(v));if(!n){n=v;state.roster.push(n)}state.present.add(n);i.value='';renderRoster()};
$('#example').onclick=()=>$('#report').value='*SETUP:*\n🔴 TNL 029 - EWERSON\n🔴 TNL 073 - CLAYTON\n🔴 TNL 077 - WENDEL\n🔴 TNL 112 - LUCIANO\n🔴 TNL 139 - JULIANO\n\n*MAQUINAS EM AJUSTES:*\nTNL 061 - EVERSON\n\n*PRÓXIMOS SETUPS:*\n🔴 TNL 027 - Setup 2°T (18:00)\n🔴 TNL 135 - Setup 2°T (18:30)\n🔴 TNL 130 - Setup 2°T (19:00)\n🔴 TNL 005 - Setup 2°T (20:30)';
$('#parse').onclick=()=>{if(!parseReport($('#report').value)){toast('Nenhuma atividade válida');return}state.step=2;update()};$('#back').onclick=()=>{if(state.step>0){state.step--;update()}};$('#next').onclick=()=>{if(state.step===0&&state.present.size<2){toast('Selecione ao menos 2 preparadores');return}if(state.step===1){if(!parseReport($('#report').value)){toast('Cole um relatório válido');return}state.step=2}else if(state.step===2){if(nextActivity()){toast('Defina o jantar de todos antes de concluir');return}state.step=3}else if(state.step===3)state.step=2;else state.step++;update()};renderRoster();update();})();