(()=>{'use strict';
const BASE=['Lucas V.','Lucas R.','Marlon','Ewerson','Everson','Clayton','Wendel','Gabriel','Adriano','Luciano','Juliano','Nattan','Marcio','Christoffer','Patrício','Mateus','Alan','Shaiane','Willians'];
const SLOTS=['18:00','18:30','19:00','19:30','20:00','20:30'],END=1440,MOVE=10,MAX_SCENARIOS=5000;
const state={step:0,roster:[...BASE],present:new Set(),activities:[],people:[],pi:0,ai:0,meals:{},covers:{},futureOwners:{},lastAnalysis:0,lastPlan:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim(),uid=()=>Math.random().toString(36).slice(2),toMin=t=>{const[h,m]=String(t||'00:00').split(':').map(Number);return h*60+m},toTime=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,overlap=(a,b,c,d)=>Math.max(a,c)<Math.min(b,d);
function aliases(n){const u=norm(n);if(u==='LUCAS V.')return['LUCAS V.','LUCAS V','LUCAS'];if(u==='LUCAS R.')return['LUCAS R.','LUCAS R'];if(u==='MARCIO')return['MARCIO','MÁRCIO'];return[n]}
function toast(x){const e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1700)}
function renderRoster(){$('#roster').innerHTML=state.roster.map(n=>`<button class="chip ${state.present.has(n)?'sel':''}" data-person="${n}">${n}</button>`).join('');$$('[data-person]').forEach(b=>b.onclick=()=>{state.present.has(b.dataset.person)?state.present.delete(b.dataset.person):state.present.add(b.dataset.person);renderRoster()});$('#count').textContent=`(${state.present.size})`}
function ownerOf(line){const u=norm(line);return [...state.present].sort((a,b)=>b.length-a.length).find(n=>aliases(n).some(a=>new RegExp(`(^|[^A-Z0-9])${norm(a).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}([^A-Z0-9]|$)`).test(u)))||null}
function parseReport(raw){let sec='ignore';const map=new Map(),futures=[];for(const r of raw.split(/\n/)){const line=r.trim();if(!line)continue;const u=norm(line).replace(/\*/g,'').replace(/:$/,'');if(u==='SETUP'||u.includes('MAQUINAS EM SETUP')){sec='setup';continue}if(u==='AJUSTES'||u.includes('MAQUINAS EM AJUSTES')){sec='adjust';continue}if(u.includes('PROXIMOS SETUPS')){sec='future';continue}if(u.includes('MANUTENCAO')||u.includes('SETUPS 1')||u.includes('SETUPS 3')||u.includes('SELECAO')||u.includes('BOM TRABALHO')){sec='ignore';continue}if(!['setup','adjust','future'].includes(sec))continue;const mm=line.match(/TNL\s*0*(\d{1,3})/i);if(!mm)continue;const machine=`TNL ${String(mm[1]).padStart(3,'0')}`,time=(line.match(/\b(\d{1,2}:\d{2})\b/)||[])[1]||'20:30';if(sec==='future'){if(!futures.some(x=>x.machine===machine))futures.push({id:uid(),type:'future',machine,start:time});continue}const owner=ownerOf(line);if(line.includes('✅')){map.delete(machine);continue}if(owner)map.set(machine,{id:uid(),type:sec,machine,owner,status:null,finish:null,coverTime:null})}
state.activities=[...map.values(),...futures];state.people=[...new Set([...state.present].filter(n=>state.activities.some(a=>a.owner===n)))];state.pi=0;state.ai=0;state.meals={};state.covers={};state.futureOwners={};state.lastAnalysis=0;state.lastPlan=null;return state.activities.length>0}
const personActs=n=>state.activities.filter(a=>a.owner===n),currentPerson=()=>state.people[state.pi]||null,currentAct=()=>{const p=currentPerson();return p?personActs(p)[state.ai]||null:null};
function initialBusy(name){const acts=personActs(name);if(!acts.length)return 1080;let until=1080;for(const a of acts){if(a.status==='finish'&&a.finish)until=Math.max(until,toMin(a.finish));else if(a.status==='cover')continue;else return END}return until}
function seedEvents(extraCover=null){const events={};for(const n of state.present)events[n]=[];for(const [n,t] of Object.entries(state.meals))events[n].push({s:toMin(t),e:toMin(t)+60,k:'meal'});for(const [id,c] of Object.entries(state.covers)){if(extraCover&&id===extraCover.id)continue;events[c.who]?.push({s:toMin(c.time),e:toMin(c.time)+60,k:'cover'});events[c.owner]?.push({s:toMin(c.time),e:toMin(c.time)+60,k:'meal'})}if(extraCover){events[extraCover.who]?.push({s:extraCover.s,e:extraCover.e,k:'cover'});events[extraCover.owner]?.push({s:extraCover.s,e:extraCover.e,k:'meal'})}return events}
function freeFor(name,s,e,events){return initialBusy(name)+MOVE<=s&&!events[name].some(x=>overlap(x.s,x.e,s,e))}
function clonePlan(p){const events={};for(const [n,ev] of Object.entries(p.events))events[n]=ev.map(x=>({...x}));return{events,owners:{...p.owners},meals:{...p.meals},covered:p.covered,delay:p.delay,late:p.late,reserve:p.reserve}}
function comparePlan(a,b){const ka=[a.covered,-a.delay,a.reserve,a.late],kb=[b.covered,-b.delay,b.reserve,b.late];for(let i=0;i<ka.length;i++)if(ka[i]!==kb[i])return kb[i]-ka[i];return 0}
function solveGlobal(extraCover=null){const futures=state.activities.filter(a=>a.type==='future').sort((a,b)=>toMin(a.start)-toMin(b.start));let evaluated=0;let beam=[{events:seedEvents(extraCover),owners:{},meals:{...state.meals},covered:0,delay:0,late:0,reserve:0}];
for(const f of futures){const next=[];const target=toMin(f.start);for(const p of beam){if(evaluated>=MAX_SCENARIOS)break;let made=false;for(const n of state.present){if(evaluated>=MAX_SCENARIOS)break;if(!freeFor(n,target,END,p.events))continue;const q=clonePlan(p);q.owners[f.id]=n;q.events[n].push({s:target,e:END,k:'future'});q.covered++;next.push(q);evaluated++;made=true}if(!made){const q=clonePlan(p);next.push(q);evaluated++}}beam=next.sort(comparePlan).slice(0,180);if(!beam.length)break}
const mealPeople=[...state.present].filter(n=>!state.meals[n]&&!(extraCover&&extraCover.owner===n));for(const n of mealPeople){const next=[];for(const p of beam){if(evaluated>=MAX_SCENARIOS)break;let any=false;for(const t of [...SLOTS].reverse()){if(evaluated>=MAX_SCENARIOS)break;const s=toMin(t),e=s+60;if(!freeFor(n,s,e,p.events))continue;const q=clonePlan(p);q.meals[n]=t;q.events[n].push({s,e,k:'meal'});q.late+=s;q.reserve+=[...state.present].filter(x=>x!==n&&freeFor(x,s,e,q.events)).length;next.push(q);evaluated++;any=true}if(!any){const q=clonePlan(p);next.push(q);evaluated++}}beam=next.sort(comparePlan).slice(0,180);if(!beam.length||evaluated>=MAX_SCENARIOS)break}
const best=beam.sort(comparePlan)[0]||{events:seedEvents(extraCover),owners:{},meals:{},covered:0,delay:0,late:0,reserve:0};state.lastAnalysis=evaluated;return{best,evaluated,total:futures.length}}
function coverageOptions(a){const out=[];for(const t of SLOTS){const s=toMin(t),e=s+60;for(const n of state.present){if(n===a.owner||initialBusy(n)+MOVE>s)continue;const sim=solveGlobal({id:a.id,who:n,owner:a.owner,s,e});out.push({name:n,time:t,plan:sim.best,evaluated:sim.evaluated,total:sim.total})}}out.sort((x,y)=>comparePlan(x.plan,y.plan));state.lastAnalysis=out.reduce((m,x)=>Math.max(m,x.evaluated),0);return out}
function previewPlan(){const sim=solveGlobal();state.lastPlan=sim.best;state.lastAnalysis=sim.evaluated;return sim}
function productionPanel(){const futures=state.activities.filter(a=>a.type==='future').sort((a,b)=>toMin(a.start)-toMin(b.start)),done=state.activities.filter(a=>a.type!=='future'&&a.status).length,totalDec=state.activities.filter(a=>a.type!=='future').length,sim=previewPlan(),confirmed=done===totalDec?sim.best.covered:0,next=futures.find(f=>!sim.best.owners[f.id])||futures[0];return `<div class="ops-panel"><div class="ops-label">SITUAÇÃO DA PRODUÇÃO</div><div class="ops-summary"><div><span>Próximos setups</span><strong>${confirmed}/${futures.length||0} confirmados</strong></div><div><span>Análise interna</span><strong>${sim.evaluated.toLocaleString('pt-BR')} cenários</strong></div></div>${next?`<div class="next-priority"><small>${sim.best.owners[next.id]?'PRÓXIMO SETUP':'PRÓXIMA PRIORIDADE'}</small><time>${next.start}</time><b>${next.machine}</b><span>${done===totalDec?(sim.best.owners[next.id]||'Sem responsável'):'Aguardando conclusão da ronda'}</span></div>`:'<div class="next-priority ok"><small>PROGRAMAÇÃO</small><b>Sem próximos setups informados</b></div>'}</div>`}
function recommendationHTML(a){const list=coverageOptions(a),best=list[0];if(!best)return `<div class="recommendation danger"><small>RECOMENDAÇÃO</small><h3>Continuar a ronda</h3><p>Ainda não existe encaixe seguro com as informações atuais.</p></div>`;const protectedCount=best.plan.covered;return `<div class="recommendation"><small>RECOMENDAÇÃO</small><h3>${best.name} cobre ${a.owner}</h3><div class="rec-line"><time>${best.time}</time><span>${a.machine}</span></div><p>Melhor combinação encontrada para a programação atual.</p><div class="analysis-note">${best.evaluated.toLocaleString('pt-BR')} cenários analisados • ${protectedCount}/${best.total} próximos setups atendidos</div><button class="btn primary full" data-apply-cover="${best.name}" data-time="${best.time}">Aplicar plano</button><details><summary>Ver outra opção</summary>${list.slice(1,4).map(x=>`<button class="alt-btn" data-apply-cover="${x.name}" data-time="${x.time}"><strong>${x.name}</strong><small>${x.time} • ${x.plan.covered}/${x.total} setups</small></button>`).join('')}</details></div>`}
function renderRound(){const p=currentPerson(),a=currentAct();if(!p||!a){const sim=solveGlobal();state.futureOwners=sim.best.owners;state.meals={...sim.best.meals,...state.meals};state.step=3;update();return}const done=state.activities.filter(x=>x.type!=='future'&&x.status).length,total=state.activities.filter(x=>x.type!=='future').length;$('#round').innerHTML=`${productionPanel()}<div class="decision-progress">${done}/${total} decisões concluídas</div><div class="card decision-card"><div class="activity-head"><div><div class="machine">${a.type==='setup'?'🔴':'🟡'} ${a.machine}</div><div class="owner">${p}</div></div><span class="badge">${a.type==='setup'?'SETUP':'AJUSTE'}</span></div>${a.status?`<div class="locked">✓ ${a.status==='finish'?`Finaliza ${a.finish}`:`${state.covers[a.id]?.who} cobre às ${a.coverTime}`}</div><button class="btn secondary full edit" data-edit="1">Editar</button>`:`<div class="question">O que vai acontecer?</div><div class="choice"><button data-status="finish">Vai terminar</button><button data-status="cover">Precisa revezar</button></div>`}<div id="decision"></div></div>`;bindRound(a)}
function advance(){const p=currentPerson(),acts=personActs(p);if(state.ai<acts.length-1)state.ai++;else if(state.pi<state.people.length-1){state.pi++;state.ai=0}else{const sim=solveGlobal();state.futureOwners=sim.best.owners;state.meals={...sim.best.meals,...state.meals};state.step=3}update()}
function bindRound(a){$('[data-edit]')&&($('[data-edit]').onclick=()=>{a.status=null;a.finish=null;delete state.covers[a.id];delete state.meals[a.owner];renderRound()});$$('[data-status]').forEach(b=>b.onclick=()=>{if(b.dataset.status==='finish'){$('#decision').innerHTML=`<div class="field"><label>Previsão de término</label><input id="finish" class="input" type="time" value="19:00"></div><button id="confirmFinish" class="btn primary full compact-action">Confirmar</button>`;$('#confirmFinish').onclick=()=>{a.status='finish';a.finish=$('#finish').value;advance()}}else{$('#decision').innerHTML=`<div id="rec">${recommendationHTML(a)}</div>`;$$('[data-apply-cover]').forEach(x=>x.onclick=()=>{a.status='cover';a.coverTime=x.dataset.time;state.meals[a.owner]=x.dataset.time;state.covers[a.id]={who:x.dataset.applyCover,time:x.dataset.time,owner:a.owner,machine:a.machine};advance()})}})}
function allEvents(){const sim=solveGlobal();state.futureOwners=sim.best.owners;state.meals={...sim.best.meals,...state.meals};const rows=[];Object.entries(state.meals).forEach(([n,t])=>rows.push({n,s:toMin(t),text:`Jantar ${t}–${toTime(toMin(t)+60)}`}));Object.values(state.covers).forEach(c=>rows.push({n:c.who,s:toMin(c.time),text:`Revezar ${c.owner} — ${c.machine}`}));Object.entries(state.futureOwners).forEach(([id,n])=>{const f=state.activities.find(a=>a.id===id);if(f)rows.push({n,s:toMin(f.start),text:`Iniciar ${f.machine}`})});return rows.sort((a,b)=>a.s-b.s)}
function whatsapp(){const ev=allEvents(),by={};ev.forEach(x=>(by[x.n]||(by[x.n]=[])).push(x));let txt='*REVEZAMENTO*\n\n';for(const n of Object.keys(by)){txt+=`*${n.toUpperCase()}*\n`;for(const x of by[n])txt+=`${toTime(x.s)} - ${x.text}\n`;txt+='\n'}txt+='*PRÓXIMOS SETUPS*\n\n';for(const f of state.activities.filter(a=>a.type==='future').sort((a,b)=>toMin(a.start)-toMin(b.start)))txt+=`${f.start} - ${f.machine} - ${state.futureOwners[f.id]||'SEM RESPONSÁVEL'}\n`;return txt}
function renderFinal(){const ev=allEvents(),by={};ev.forEach(x=>(by[x.n]||(by[x.n]=[])).push(x));const open=state.activities.filter(a=>a.type==='future'&&!state.futureOwners[a.id]),unresolved=state.activities.filter(a=>a.type!=='future'&&!a.status);$('#final').innerHTML=`<div class="validation ${open.length||unresolved.length?'warnbox':'okbox'}"><strong>${open.length||unresolved.length?'Plano com pendências':'✓ Plano pronto'}</strong><span>${state.lastAnalysis.toLocaleString('pt-BR')} cenários analisados • ${open.length?`${open.length} setup(s) sem responsável`:unresolved.length?`${unresolved.length} decisão(ões) faltando`:'Programação organizada'}</span></div><div class="report-actions"><button id="copyWA" class="btn primary full">📋 Copiar para WhatsApp</button><button id="showText" class="btn secondary full">Ver texto completo</button></div>${Object.entries(by).map(([n,rows])=>`<div class="card person-report"><h3>${n}</h3>${rows.map(x=>`<div class="report-line"><time>${toTime(x.s)}</time><span>${x.text}</span></div>`).join('')}</div>`).join('')}<textarea id="waText" class="wa-text" hidden>${whatsapp()}</textarea>`;$('#copyWA').onclick=async()=>{try{await navigator.clipboard.writeText(whatsapp());toast('Relatório copiado')}catch{const t=$('#waText');t.hidden=false;t.select();document.execCommand('copy');toast('Relatório copiado')}};$('#showText').onclick=()=>{$('#waText').hidden=!$('#waText').hidden}}
function update(){$$('.step').forEach((e,i)=>e.classList.toggle('active',i===state.step));$$('.progress span').forEach((e,i)=>e.classList.toggle('on',i<=state.step));$('#back').style.visibility=state.step===0?'hidden':'visible';$('#next').textContent=state.step===2?'Ver relatório':state.step===3?'Voltar à ronda':'Continuar';if(state.step===2)renderRound();if(state.step===3)renderFinal();scrollTo(0,0)}
$('#addName').onclick=()=>{const i=$('#newName'),v=i.value.trim();if(!v)return;let n=state.roster.find(x=>norm(x)===norm(v));if(!n){n=v;state.roster.push(n)}state.present.add(n);i.value='';renderRoster()};$('#example').onclick=()=>$('#report').value='*MAQUINAS EM SETUP*\n🔴 TNL 029 - EWERSON\n🔴 TNL 073 - CLAYTON\n\n*MAQUINAS EM AJUSTES*\nTNL 033 - ALAN\n\n*PRÓXIMOS SETUPS*\n🔴 TNL 027 - Setup 2°T (18:00)\n🔴 TNL 130 - Setup 2°T (19:00)\n🔴 TNL 005 - Setup 2°T (20:30)';$('#parse').onclick=()=>{if(!parseReport($('#report').value)){toast('Nenhuma atividade válida');return}state.step=2;update()};$('#back').onclick=()=>{if(state.step>0){state.step--;update()}};$('#next').onclick=()=>{if(state.step===0&&state.present.size<2){toast('Selecione ao menos 2 preparadores');return}if(state.step===1){if(!parseReport($('#report').value)){toast('Cole um relatório válido');return}state.step=2}else if(state.step===2)state.step=3;else if(state.step===3)state.step=2;else state.step++;update()};renderRoster();update();})();