(()=>{'use strict';
const BASE=['Lucas V.','Lucas R.','Marlon','Ewerson','Everson','Clayton','Wendel','Gabriel','Adriano','Luciano','Juliano','Nattan','Marcio','Christoffer','Patrício','Mateus','Alan','Shaiane','Willians'];
const SLOTS=['18:00','18:30','19:00','19:30','20:00','20:30'],END=1440,MOVE=10;
const state={step:0,roster:[...BASE],present:new Set(),activities:[],people:[],personIndex:0,activityIndex:0,meals:{},covers:{},futureOwners:{}};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim(),uid=()=>Math.random().toString(36).slice(2),toMin=t=>{const[h,m]=String(t||'00:00').split(':').map(Number);return h*60+m},toTime=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`,overlap=(a,b,c,d)=>Math.max(a,c)<Math.min(b,d);
function toast(x){const e=$('#toast');e.textContent=x;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),1500)}
function renderRoster(){$('#roster').innerHTML=state.roster.map(n=>`<button class="chip ${state.present.has(n)?'sel':''}" data-person="${n}">${n}</button>`).join('');$$('[data-person]').forEach(b=>b.onclick=()=>{state.present.has(b.dataset.person)?state.present.delete(b.dataset.person):state.present.add(b.dataset.person);renderRoster()});$('#count').textContent=`(${state.present.size})`}
function ownerOf(line){const u=norm(line);return [...state.present].sort((a,b)=>b.length-a.length).find(n=>u.includes(norm(n)))||null}
function parseReport(raw){let section='ignore';const acts=[];for(const line0 of raw.split(/\n/)){const line=line0.trim();if(!line)continue;const u=norm(line).replace(/\*/g,'');if(u==='SETUP'||u.includes('MAQUINAS EM SETUP')){section='setup';continue}if(u.includes('MAQUINAS EM AJUSTES')||u==='AJUSTES'||u==='AJUSTES:'){section='adjust';continue}if(u.includes('PROXIMOS SETUPS')){section='future';continue}if(u.includes('MANUTENCAO')||u.includes('SETUPS 1')||u.includes('SETUPS 3')||u.includes('SELECAO')){section='ignore';continue}if(line.includes('✅')||!['setup','adjust','future'].includes(section))continue;const mm=line.match(/TNL\s*0*(\d{1,3})/i);if(!mm)continue;const machine=`TNL ${String(mm[1]).padStart(3,'0')}`,time=(line.match(/\b(\d{1,2}:\d{2})\b/)||[])[1]||'20:30';if(section==='future'){if(!acts.some(a=>a.type==='future'&&a.machine===machine))acts.push({id:uid(),type:'future',machine,start:time});continue}const owner=ownerOf(line);if(owner&&!acts.some(a=>a.machine===machine))acts.push({id:uid(),type:section,machine,owner,status:null,finish:null,meal:'20:30',coverTime:'20:30'})}state.activities=acts;state.people=[...new Set(acts.filter(a=>a.owner).map(a=>a.owner))];state.personIndex=0;state.activityIndex=0;state.meals={};state.covers={};state.futureOwners={};return acts.length>0}
const personActs=n=>state.activities.filter(a=>a.owner===n),currentPerson=()=>state.people[state.personIndex]||null,currentAct=()=>{const p=currentPerson();return p?personActs(p)[state.activityIndex]||null:null};
function busyUntil(name){const acts=personActs(name);if(!acts.length)return 1080;let max=1080;for(const a of acts){if(a.status==='finish'&&a.finish)max=Math.max(max,toMin(a.finish));else if(a.status==='cover'||a.status===null)return END}return max}
function confirmedEvents(name,ignore=null){const ev=[],meal=state.meals[name];if(meal)ev.push({s:toMin(meal),e:toMin(meal)+60,label:'Jantar'});Object.entries(state.covers).forEach(([id,c])=>{if(id!==ignore&&c.who===name)ev.push({s:toMin(c.time),e:toMin(c.time)+60,label:`Cobre ${c.owner} — ${c.machine}`})});Object.entries(state.futureOwners).forEach(([id,n])=>{if(n===name){const f=state.activities.find(a=>a.id===id);ev.push({s:toMin(f.start),e:END,label:`Inicia ${f.machine}`})}});return ev}
function canDo(name,s,e,ignore=null){if(busyUntil(name)+MOVE>s)return false;return !confirmedEvents(name,ignore).some(x=>overlap(x.s,x.e,s,e))}
function futureValue(name,after){let v=0;for(const f of state.activities.filter(a=>a.type==='future'&&toMin(a.start)>=after&&!state.futureOwners[a.id]))if(canDo(name,toMin(f.start),END))v+=toMin(f.start)<1200?40:15;return v}
function mealPossible(name,events=[],deadline=END){if(state.meals[name])return true;const free=busyUntil(name);return SLOTS.some(t=>{const s=toMin(t),e=s+60;return s>=free&&e<=deadline&&!events.some(x=>overlap(x.s,x.e,s,e))})}
function evaluateCandidate(name,a){const s=toMin(a.coverTime),e=s+60;if(name===a.owner||!canDo(name,s,e,a.id))return null;const ev=confirmedEvents(name,a.id).concat({s,e});if(!mealPossible(name,ev,END))return null;const fv=futureValue(name,e),alternatives=[...state.present].filter(n=>n!==name&&n!==a.owner&&canDo(n,s,e)).length,margin=s-busyUntil(name);return{name,score:300+Math.min(margin,60)+alternatives*20-fv,margin,fv,alternatives,risks:[...(margin<15?[`margem curta: ${margin} min`]:[]),...(fv>=40?['pode fazer falta em setup próximo']:[])],reason:fv?'Funciona, mas possui valor futuro para outros setups.':'Encaixa sem comprometer os próximos eventos conhecidos.'}}
const suggestions=a=>[...state.present].map(n=>evaluateCandidate(n,a)).filter(Boolean).sort((x,y)=>y.score-x.score);
function conditional(a){const s=toMin(a.coverTime);for(const[id,c]of Object.entries(state.covers)){if(toMin(c.time)!==s)continue;const old=state.activities.find(x=>x.id===id);for(const n of state.present){if([a.owner,old.owner,c.who].includes(n))continue;if(canDo(n,s,s+60,id))return{title:'Troca inteligente',text:`Trocar ${c.who} por ${n} na ${old.machine}. Assim, ${c.who} fica livre para cobrir ${a.owner} na ${a.machine}.`,swap:{id,newWho:n,freed:c.who}}}}return null}
function reserveFuture(){for(const f of state.activities.filter(a=>a.type==='future'&&!state.futureOwners[a.id]).sort((a,b)=>toMin(a.start)-toMin(b.start))){const s=toMin(f.start),opts=[...state.present].filter(n=>canDo(n,s,END)&&mealPossible(n,confirmedEvents(n),s)).map(n=>({n,v:futureValue(n,s)})).sort((a,b)=>a.v-b.v);if(opts[0])state.futureOwners[f.id]=opts[0].n}}
function advance(){const p=currentPerson(),acts=personActs(p);if(state.activityIndex<acts.length-1)state.activityIndex++;else if(state.personIndex<state.people.length-1){state.personIndex++;state.activityIndex=0}else{reserveFuture();state.step=3}update()}
function personTabs(){return `<div class="person-tabs">${state.people.map((p,i)=>{const done=personActs(p).every(a=>a.status);return `<button class="person-pill ${i===state.personIndex?'active':''} ${done?'done':''}" data-jump="${i}">${done?'✓ ':''}${p}</button>`}).join('')}</div>`}
function recommendationHTML(a){const list=suggestions(a),best=list[0];if(best)return `<div class="suggestion"><div class="suggestion-title">MELHOR ENCAIXE AGORA</div><div class="suggestion-name">${best.name}</div><div class="reason">${best.reason}</div><div class="impact"><div>✓ ${best.alternatives} alternativa(s) ainda permanecem</div><div>${best.fv?'⚠':'✓'} Impacto futuro: ${best.fv?'atenção':'baixo'}</div>${best.risks.map(r=>`<div>⚠ ${r}</div>`).join('')}</div><button class="btn primary" style="width:100%;margin-top:12px" data-confirm-cover="${best.name}">Confirmar ${best.name}</button><details style="margin-top:10px"><summary class="muted">Ver outras opções</summary><div class="alt-list">${list.slice(1,5).map(x=>`<button class="alt-btn" data-confirm-cover="${x.name}"><div class="alt-top"><strong>${x.name}</strong><span class="tag ${x.risks.length?'warn':'good'}">${x.risks.length?'COM RISCO':'POSSÍVEL'}</span></div><div class="small">${x.reason}</div></button>`).join('')}</div></details></div>`;const c=conditional(a);return `<div class="suggestion bad"><div class="suggestion-title">NÃO HÁ ENCAIXE DIRETO</div><div class="suggestion-name">Precisa reorganizar</div><div class="reason">${c?c.text:'Nenhum preparador conhecido consegue assumir sem conflito. Continue a ronda ou altere o horário.'}</div>${c?`<button class="btn primary" style="width:100%;margin-top:12px" data-swap="1">Aplicar troca sugerida</button>`:''}</div>`}
function renderRound(){const p=currentPerson(),a=currentAct();if(!p||!a){state.step=3;update();return}const completed=state.activities.filter(x=>x.type!=='future'&&x.status).length,total=state.activities.filter(x=>x.type!=='future').length;$('#round').innerHTML=`${personTabs()}<div class="roundbar"><div><div class="person-name">${p}</div><div class="counter">${state.activityIndex+1} de ${personActs(p).length} atividades deste preparador • ${completed}/${total} da ronda</div></div></div><div class="card"><div class="activity-head"><div><div class="machine">${a.type==='setup'?'🔴':'🟡'} ${a.machine}</div><div class="owner">${p}</div></div><span class="badge">${a.type==='setup'?'SETUP':'AJUSTE'}</span></div>${a.status?`<div class="locked">✓ Decisão confirmada: ${a.status==='finish'?`termina às ${a.finish}`:`revezamento às ${a.coverTime} com ${state.covers[a.id]?.who||'não definido'}`}</div><button class="btn secondary" style="width:100%;margin-top:10px" data-edit="1">Editar decisão</button>`:`<div class="question">Como ficará no horário da janta?</div><div class="choice"><button data-status="finish">Vai terminar</button><button data-status="cover">Precisa revezar</button></div>`}<div id="decision"></div></div>`;bindRound(a)}
function bindRound(a){$$('[data-jump]').forEach(b=>b.onclick=()=>{state.personIndex=+b.dataset.jump;state.activityIndex=0;renderRound()});$('[data-edit]')&&($('[data-edit]').onclick=()=>{a.status=null;a.finish=null;delete state.covers[a.id];renderRound()});$$('[data-status]').forEach(b=>b.onclick=()=>{if(b.dataset.status==='finish'){$('#decision').innerHTML=`<div class="field"><label>Que horas termina?</label><input id="finish" class="input" type="time" value="19:00"></div><div class="field"><label>Preferência de janta</label><input id="meal" class="input" type="time" value="20:30"></div><button id="confirmFinish" class="btn primary" style="width:100%;margin-top:12px">Confirmar e próximo</button>`;$('#confirmFinish').onclick=()=>{a.status='finish';a.finish=$('#finish').value;a.meal=$('#meal').value;state.meals[a.owner]=a.meal;advance()}}else{$('#decision').innerHTML=`<div class="field"><label>Horário desejado do revezamento</label><input id="coverTime" class="input" type="time" value="20:30"></div><button id="calc" class="btn primary" style="width:100%;margin-top:12px">Buscar melhor encaixe</button><div id="rec"></div>`;$('#calc').onclick=()=>{a.coverTime=$('#coverTime').value;$('#rec').innerHTML=recommendationHTML(a);$$('[data-confirm-cover]').forEach(x=>x.onclick=()=>{a.status='cover';state.covers[a.id]={who:x.dataset.confirmCover,time:a.coverTime,owner:a.owner,machine:a.machine};advance()});const c=conditional(a);$('[data-swap]')&&($('[data-swap]').onclick=()=>{state.covers[c.swap.id].who=c.swap.newWho;a.status='cover';state.covers[a.id]={who:c.swap.freed,time:a.coverTime,owner:a.owner,machine:a.machine};advance()})}}})}
function finalEvents(){const rows=[];Object.entries(state.meals).forEach(([n,t])=>rows.push({s:toMin(t),n,text:`Jantar até ${toTime(toMin(t)+60)}`}));Object.values(state.covers).forEach(c=>rows.push({s:toMin(c.time),n:c.who,text:`Cobre ${c.owner} — ${c.machine}`}));Object.entries(state.futureOwners).forEach(([id,n])=>{const f=state.activities.find(a=>a.id===id);rows.push({s:toMin(f.start),n,text:`Inicia ${f.machine}`})});return rows.sort((a,b)=>a.s-b.s)}
function renderFinal(){reserveFuture();const rows=finalEvents(),groups={};rows.forEach(r=>(groups[r.n]||(groups[r.n]=[])).push(r));const unresolved=state.activities.filter(a=>a.type!=='future'&&!a.status);$('#final').innerHTML=`${unresolved.length?`<div class="card issue"><strong>⚠ ${unresolved.length} atividade(s) ainda sem decisão</strong></div>`:''}${Object.entries(groups).map(([n,ev])=>`<div class="card done-card"><div class="person-name">${n}</div><div class="agenda">${ev.map(x=>`<div class="event"><time>${toTime(x.s)}</time><span>${x.text}</span></div>`).join('')}</div></div>`).join('')}`}
function update(){$$('.step').forEach((e,i)=>e.classList.toggle('active',i===state.step));$$('.progress span').forEach((e,i)=>e.classList.toggle('on',i<=state.step));$('#back').style.visibility=state.step===0?'hidden':'visible';$('#next').textContent=state.step===2?'Ver plano':state.step===3?'Voltar à ronda':'Continuar';if(state.step===2)renderRound();if(state.step===3)renderFinal();scrollTo(0,0)}
$('#addName').onclick=()=>{const i=$('#newName'),v=i.value.trim();if(!v)return;let n=state.roster.find(x=>norm(x)===norm(v));if(!n){n=v;state.roster.push(n)}state.present.add(n);i.value='';renderRoster()};$('#example').onclick=()=>$('#report').value='*SETUP*\n🔴 TNL 053 - NATTAN\n🔴 TNL 076 - CLAYTON\n🔴 TNL 092 - LUCAS V.\n\n*AJUSTES*\nTNL 093 - LUCAS V.\nTNL 115 - LUCIANO\n\n*PRÓXIMOS SETUPS*\n🔴 TNL 112 - Setup 2°T (19:30)\n🔴 TNL 005 - Setup 2°T (22:20)';$('#parse').onclick=()=>{if(!parseReport($('#report').value.trim()))return toast('Nenhuma atividade encontrada');state.step=2;update()};$('#back').onclick=()=>{if(state.step>0){state.step--;update()}};$('#next').onclick=()=>{if(state.step===0&&state.present.size<2)return toast('Selecione ao menos 2');if(state.step===1){if(!parseReport($('#report').value.trim()))return toast('Cole um relatório válido');state.step=2}else if(state.step===2)state.step=3;else if(state.step===3)state.step=2;else state.step++;update()};window.__copilot={state,parseReport,suggestions,evaluateCandidate,conditional,reserveFuture};renderRoster();update();})();