(()=>{'use strict';
const $=s=>document.querySelector(s),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const shadow={meals:new Map(),covers:[],history:[]};
function people(){return [...document.querySelectorAll('[data-person].sel')].map(b=>window.NCDE.canon(b.dataset.person));}
function reportTasks(){const raw=$('#report')?.value||'';let sec='';const out=[];for(const row of raw.split(/\n/)){const line=row.trim(),u=norm(line).replace(/\*/g,'');if(!line)continue;if(u.includes('MAQUINAS EM SETUP')||u==='SETUP'){sec='setup';continue}if(u.includes('MAQUINAS EM AJUSTES')||u==='AJUSTES'){sec='adjust';continue}if(u.includes('PROXIMOS SETUPS')){sec='future';continue}if(u.includes('MANUTENCAO')||u.includes('SETUPS 1')||u.includes('SETUPS 3')||u.includes('SELECAO')||u.includes('BOM TRABALHO')){sec='';continue}if(!sec||line.includes('✅'))continue;const mm=line.match(/TNL\s*0*(\d{1,3})/i);if(!mm)continue;const machine=`TNL ${String(mm[1]).padStart(3,'0')}`;if(sec==='future'){const time=(line.match(/\b(\d{1,2}:\d{2})\b/)||[])[1]||'20:30';out.push({id:`future-${machine}-${time}`,type:'future',machine,start:time,assignee:null});continue}const owner=people().sort((a,b)=>b.length-a.length).find(p=>norm(line).includes(norm(p).replace(/\.$/,'')))||null;if(owner)out.push({id:`current-${machine}`,type:sec,machine,owner,start:'14:30',end:'18:00'});}return out;}
function currentContext(){const round=$('#round');if(!round)return null;const text=round.innerText||'';const machine=(text.match(/TNL\s*\d{1,3}/i)||[])[0];const owner=(round.querySelector('.round-head h2')?.textContent||'').trim();return machine&&owner?{machine:machine.replace(/TNL\s*0*(\d{1,3})/i,(_,n)=>`TNL ${String(n).padStart(3,'0')}`),owner:window.NCDE.canon(owner)}:null;}
function plan(extra=null){const tasks=reportTasks();const meals=[...shadow.meals].map(([person,start],i)=>({id:`meal-${i}`,person,start}));const covers=shadow.covers.map((c,i)=>({id:`cover-${i}`,...c}));if(extra?.meal){shadow.meals.set(extra.meal.person,extra.meal.start);meals.push(extra.meal)}if(extra?.cover)covers.push(extra.cover);return{people:people(),tasks,meals,covers};}
function ensure(){const round=$('#round');if(!round)return null;let box=$('#ncdeLive');if(!box){box=document.createElement('div');box.id='ncdeLive';box.className='strategy';box.style.marginBottom='14px';round.prepend(box);}return box;}
function render(extra=null){if(!window.NCDE)return;const box=ensure();if(!box)return;const result=window.NCDE.optimize(plan(extra),{limit:1200}),m=result.metrics;const visibleErrors=m.errors.filter(e=>e.code!=='FUTURE_UNASSIGNED');const open=m.errors.filter(e=>e.code==='FUTURE_UNASSIGNED').length;box.className=`strategy ${visibleErrors.length?'danger':''}`;box.innerHTML=`<div class="kicker">ANÁLISE AO VIVO • NCDE ${window.NCDE.version}</div><h3>${visibleErrors.length?'CONFLITO ANTES DE CONFIRMAR':'DECISÃO OPERACIONALMENTE POSSÍVEL'}</h3><p>${visibleErrors[0]?.message||`Nota provisória ${m.score}/100. ${open} próximo(s) setup(s) ainda aguardam responsável.`}</p><div class="factory-grid"><div><span>NOTA</span><strong>${m.score}/100</strong></div><div><span>CONFLITOS</span><strong>${visibleErrors.length}</strong></div><div><span>SETUPS ABERTOS</span><strong>${open}</strong></div><div><span>CENÁRIOS</span><strong>${result.explored}</strong></div></div>`;window.__NCDE_LIVE__=result;}
function rememberFinish(){const ctx=currentContext(),time=$('#finish')?.value;if(!ctx||!time)return;shadow.meals.set(ctx.owner,time);shadow.history.push({type:'finish',...ctx,time});}
function rememberCover(btn){const ctx=currentContext(),time=$('#coverTime')?.value,who=btn?.dataset?.confirmCover;if(!ctx||!time||!who)return;const person=window.NCDE.canon(who);shadow.meals.set(ctx.owner,time);shadow.covers=shadow.covers.filter(c=>!(c.owner===ctx.owner&&c.machine===ctx.machine));shadow.covers.push({person,owner:ctx.owner,machine:ctx.machine,start:time});shadow.history.push({type:'cover',person,owner:ctx.owner,machine:ctx.machine,time});}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.id==='confirmFinish'){const ctx=currentContext(),time=$('#finish')?.value;if(ctx&&time){const test=window.NCDE.validate(plan({meal:{person:ctx.owner,start:time}}));const err=test.errors.find(x=>x.code!=='FUTURE_UNASSIGNED');if(err){e.preventDefault();e.stopImmediatePropagation();alert(`NCDE bloqueou a decisão: ${err.message}`);render({meal:{person:ctx.owner,start:time}});return}rememberFinish();setTimeout(()=>render(),0)}if(t.dataset.confirmCover){const ctx=currentContext(),time=$('#coverTime')?.value,person=window.NCDE.canon(t.dataset.confirmCover);if(ctx&&time){const extra={cover:{person,owner:ctx.owner,machine:ctx.machine,start:time},meal:{person:ctx.owner,start:time}};const test=window.NCDE.validate(plan(extra));const err=test.errors.find(x=>x.code!=='FUTURE_UNASSIGNED');if(err){e.preventDefault();e.stopImmediatePropagation();alert(`NCDE bloqueou a decisão: ${err.message}`);render(extra);return}rememberCover(t);setTimeout(()=>render(),0)}}},true);
document.addEventListener('change',e=>{if(['finish','coverTime'].includes(e.target?.id))setTimeout(()=>render(),0)});
new MutationObserver(()=>{if($('#round')&&document.querySelector('.step.active #round'))render()}).observe(document.body,{childList:true,subtree:true});
window.NCDELive={shadow,render,reset(){shadow.meals.clear();shadow.covers=[];shadow.history=[];render()}};
})();