(()=>{'use strict';
const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const canon=n=>{const u=norm(n).replace(/\.$/,'');if(u==='LUCAS'||u==='LUCAS V')return'Lucas V.';if(u==='MARCIO')return'Marcio';return String(n||'').trim().replace(/^\*|\*$/g,'').replace(/\b\w/g,c=>c.toUpperCase())};
const toMin=t=>{const[h,m]=String(t||'00:00').split(':').map(Number);return h*60+m};
const toTime=m=>`${String(Math.floor(m/60)).padStart(2,'0')}:${String(m%60).padStart(2,'0')}`;
function parseMachines(){const raw=document.querySelector('#report')?.value||'';let sec='';const by={};for(const row of raw.split(/\n/)){const line=row.trim();const u=norm(line).replace(/\*/g,'');if(u.includes('MAQUINAS EM SETUP')){sec='setup';continue}if(u.includes('MAQUINAS EM AJUSTES')){sec='adjust';continue}if(u.includes('PROXIMOS SETUPS')||u.includes('MANUTENCAO')||u.includes('SETUPS 1')||u.includes('SETUPS 3')||u.includes('SELECAO')){sec='';continue}if(!sec||line.includes('✅'))continue;const mm=line.match(/TNL\s*0*(\d{1,3})/i);if(!mm)continue;const tail=line.split('-').slice(1).join('-').trim().replace(/^OP\s+/i,'');if(!tail)continue;const owner=canon(tail);(by[owner]||(by[owner]=[])).push({machine:`TNL ${String(mm[1]).padStart(3,'0')}`,type:sec});}return by}
function parseGenerated(txt){const meals={},coverFor={},duties={},futures=[];let person=null,section='';for(const raw of txt.split(/\n/)){const line=raw.trim();if(!line)continue;if(line==='*REVEZAMENTO*'){section='rev';continue}if(line==='*PRÓXIMOS SETUPS*'){section='future';person=null;continue}if(line==='*PENDÊNCIAS*'){section='pending';person=null;continue}if(/^\*[^*]+\*$/.test(line)&&section==='rev'){person=canon(line.slice(1,-1));continue}if(section==='future'){const m=line.match(/^(\d{1,2}:\d{2})\s*-\s*(TNL\s*\d+)\s*-\s*(.+)$/i);if(m)futures.push({time:m[1],machine:m[2].replace(/\s+/g,' '),owner:canon(m[3]),open:/SEM RESPONSAVEL/i.test(norm(m[3]))});continue}if(section!=='rev'||!person)continue;const tm=(line.match(/^(\d{1,2}:\d{2})/)||[])[1];if(!tm)continue;if(/JANTAR/i.test(line)){meals[person]=tm;continue}let m=line.match(/Revezar\s+(.+?)\s+—\s+(TNL\s*\d+)/i);if(m){const target=canon(m[1]);coverFor[target]={who:person,time:tm,machine:m[2].replace(/\s+/g,' ')};(duties[person]||(duties[person]=[])).push({time:tm,text:`Revezar ${target} — ${m[2].replace(/\s+/g,' ')}`,kind:'cover'});continue}m=line.match(/Iniciar\s+(TNL\s*\d+)/i);if(m)(duties[person]||(duties[person]=[])).push({time:tm,text:`Iniciar ${m[1].replace(/\s+/g,' ')}`,kind:'future'});}return{meals,coverFor,duties,futures}}
function rescue(data){const open=data.futures.find(f=>f.open);if(!open)return null;const fs=toMin(open.time);const all=[];for(const [p,arr] of Object.entries(data.duties))for(const d of arr)all.push({...d,person:p,start:toMin(d.time),end:d.kind==='cover'?toMin(d.time)+60:1440});
for(const ev of all.filter(x=>x.kind==='cover'&&x.end===fs)){const newStart=ev.start-30;if(newStart>=1080){const targetMatch=ev.text.match(/Revezar\s+(.+?)\s+—/i);const target=targetMatch?targetMatch[1]:'o preparador';return{person:ev.person,title:`Liberar ${ev.person} para ${open.machine}`,text:`Antecipar a janta de ${target} para ${toTime(newStart)}. ${ev.person} faz o revezamento de ${toTime(newStart)} até ${toTime(newStart+60)} e fica livre com 30 minutos de margem para iniciar ${open.machine} às ${open.time}.`,future:open}}}
const people=new Set([...Object.keys(data.meals),...Object.keys(data.duties)]);for(const p of people){const intervals=all.filter(x=>x.person===p);const conflict=intervals.some(x=>Math.max(x.start,fs)<Math.min(x.end,1440));const meal=data.meals[p];if(!conflict&&(!meal||toMin(meal)+60<=fs-10))return{person:p,title:`Usar ${p} na ${open.machine}`,text:`${p} está sem compromisso conhecido às ${open.time} e pode iniciar ${open.machine}. Confirme apenas se a atividade atual dele já terminou.`,future:open}}
return{person:null,title:`${open.machine} continua sem responsável`,text:'Não encontrei uma troca segura apenas com os horários confirmados. Volte à ronda e revise uma cobertura anterior ou antecipe uma janta.',future:open}}
function buildReport(base,machines,data,fix=null){const names=new Set([...Object.keys(machines),...Object.keys(data.meals),...Object.keys(data.duties)]);let txt='*REVEZAMENTO*\n\n';for(const n of names){txt+=`*${n.toUpperCase()}*\n`;const ms=machines[n]||[];if(ms.length)for(const m of ms)txt+=`${m.type==='setup'?'🔴':'🟡'} ${m.machine}\n`;else txt+='LIVRE NO INÍCIO DA RONDA\n';if(data.meals[n])txt+=`JANTAR ${data.meals[n]}\n`;if(data.coverFor[n])txt+=`${data.coverFor[n].who.toUpperCase()} REVEZA ${data.coverFor[n].time} — ${data.coverFor[n].machine}\n`;for(const d of data.duties[n]||[])txt+=`${d.time} - ${d.text}\n`;txt+='\n'}txt+='*PRÓXIMOS SETUPS*\n\n';for(const f of data.futures){let owner=f.open?'SEM RESPONSÁVEL':f.owner;if(fix&&f.open&&fix.person)owner=fix.person;txt+=`${f.time} - ${f.machine} - ${owner}\n`}txt+='\n*PENDÊNCIAS*\n';txt+=data.futures.some(f=>f.open)&&!(fix&&fix.person)?data.futures.filter(f=>f.open).map(f=>`${f.machine} ${f.time} - SEM RESPONSÁVEL`).join('\n'):'Nenhuma';return txt}
function enhance(){const final=document.querySelector('#final'),wa=document.querySelector('#waText');if(!final||!wa||final.dataset.v7==='1')return;final.dataset.v7='1';const machines=parseMachines(),data=parseGenerated(wa.value),fix=rescue(data);const improved=buildReport(wa.value,machines,data,null);wa.value=improved;const actions=final.querySelector('.report-actions');if(fix&&actions){const box=document.createElement('div');box.className='strategy '+(fix.person?'':'danger');box.innerHTML=`<div class="kicker">${fix.person?'CORREÇÃO SUGERIDA':'ATENÇÃO'}</div><h3>${fix.title}</h3><p>${fix.text}</p>${fix.person?'<button id="applyFixV7" class="btn primary full">Aplicar no relatório</button>':''}`;actions.before(box);if(fix.person)box.querySelector('#applyFixV7').onclick=()=>{wa.value=buildReport('',machines,data,fix);box.innerHTML=`<div class="kicker">CORREÇÃO APLICADA AO TEXTO</div><h3>${fix.person} → ${fix.future.machine}</h3><p>Volte à ronda para confirmar operacionalmente essa mudança antes de enviar.</p>`}}
const copy=final.querySelector('#copyWA');if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(wa.value);document.querySelector('#toast').textContent='Relatório detalhado copiado';document.querySelector('#toast').classList.add('show');setTimeout(()=>document.querySelector('#toast').classList.remove('show'),1600)}catch{wa.hidden=false;wa.select();document.execCommand('copy')}}}
new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});enhance();})();